# CMake generated Testfile for 
# Source directory: D:/code/signal-transmission-model-cpp/tests
# Build directory: D:/code/signal-transmission-model-cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SignalTransmissionModelTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_signal_transmission.exe")
  set_tests_properties(SignalTransmissionModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;204;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SignalTransmissionModelTest "D:/code/signal-transmission-model-cpp/bin/Release/test_signal_transmission.exe")
  set_tests_properties(SignalTransmissionModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;204;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SignalTransmissionModelTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_signal_transmission.exe")
  set_tests_properties(SignalTransmissionModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;204;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SignalTransmissionModelTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_signal_transmission.exe")
  set_tests_properties(SignalTransmissionModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;204;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(SignalTransmissionModelTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CommunicationDistanceModelTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_communication_distance.exe")
  set_tests_properties(CommunicationDistanceModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;205;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CommunicationDistanceModelTest "D:/code/signal-transmission-model-cpp/bin/Release/test_communication_distance.exe")
  set_tests_properties(CommunicationDistanceModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;205;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CommunicationDistanceModelTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_communication_distance.exe")
  set_tests_properties(CommunicationDistanceModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;205;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CommunicationDistanceModelTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_communication_distance.exe")
  set_tests_properties(CommunicationDistanceModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;205;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(CommunicationDistanceModelTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CommunicationReceiveModelTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_communication_receive.exe")
  set_tests_properties(CommunicationReceiveModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;206;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CommunicationReceiveModelTest "D:/code/signal-transmission-model-cpp/bin/Release/test_communication_receive.exe")
  set_tests_properties(CommunicationReceiveModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;206;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CommunicationReceiveModelTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_communication_receive.exe")
  set_tests_properties(CommunicationReceiveModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;206;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CommunicationReceiveModelTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_communication_receive.exe")
  set_tests_properties(CommunicationReceiveModelTest PROPERTIES  LABELS "unit;basic" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;206;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(CommunicationReceiveModelTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CommunicationAntiJamModelTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_communication_anti_jam.exe")
  set_tests_properties(CommunicationAntiJamModelTest PROPERTIES  LABELS "unit;antijam" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;209;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CommunicationAntiJamModelTest "D:/code/signal-transmission-model-cpp/bin/Release/test_communication_anti_jam.exe")
  set_tests_properties(CommunicationAntiJamModelTest PROPERTIES  LABELS "unit;antijam" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;209;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CommunicationAntiJamModelTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_communication_anti_jam.exe")
  set_tests_properties(CommunicationAntiJamModelTest PROPERTIES  LABELS "unit;antijam" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;209;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CommunicationAntiJamModelTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_communication_anti_jam.exe")
  set_tests_properties(CommunicationAntiJamModelTest PROPERTIES  LABELS "unit;antijam" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;209;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(CommunicationAntiJamModelTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CommunicationJammerModelTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_communication_jammer.exe")
  set_tests_properties(CommunicationJammerModelTest PROPERTIES  LABELS "unit;jammer" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;210;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CommunicationJammerModelTest "D:/code/signal-transmission-model-cpp/bin/Release/test_communication_jammer.exe")
  set_tests_properties(CommunicationJammerModelTest PROPERTIES  LABELS "unit;jammer" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;210;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CommunicationJammerModelTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_communication_jammer.exe")
  set_tests_properties(CommunicationJammerModelTest PROPERTIES  LABELS "unit;jammer" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;210;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CommunicationJammerModelTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_communication_jammer.exe")
  set_tests_properties(CommunicationJammerModelTest PROPERTIES  LABELS "unit;jammer" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;210;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(CommunicationJammerModelTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CommunicationModelApiTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_communication_model_api.exe")
  set_tests_properties(CommunicationModelApiTest PROPERTIES  LABELS "unit;api" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;211;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CommunicationModelApiTest "D:/code/signal-transmission-model-cpp/bin/Release/test_communication_model_api.exe")
  set_tests_properties(CommunicationModelApiTest PROPERTIES  LABELS "unit;api" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;211;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CommunicationModelApiTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_communication_model_api.exe")
  set_tests_properties(CommunicationModelApiTest PROPERTIES  LABELS "unit;api" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;211;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CommunicationModelApiTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_communication_model_api.exe")
  set_tests_properties(CommunicationModelApiTest PROPERTIES  LABELS "unit;api" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;211;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(CommunicationModelApiTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(AntiJamParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_anti_jam_parameter_config.exe")
  set_tests_properties(AntiJamParameterConfigTest PROPERTIES  LABELS "unit;config;antijam" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;214;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(AntiJamParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/Release/test_anti_jam_parameter_config.exe")
  set_tests_properties(AntiJamParameterConfigTest PROPERTIES  LABELS "unit;config;antijam" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;214;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(AntiJamParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_anti_jam_parameter_config.exe")
  set_tests_properties(AntiJamParameterConfigTest PROPERTIES  LABELS "unit;config;antijam" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;214;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(AntiJamParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_anti_jam_parameter_config.exe")
  set_tests_properties(AntiJamParameterConfigTest PROPERTIES  LABELS "unit;config;antijam" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;214;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(AntiJamParameterConfigTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(JammerParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_jammer_parameter_config.exe")
  set_tests_properties(JammerParameterConfigTest PROPERTIES  LABELS "unit;config;jammer" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;215;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(JammerParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/Release/test_jammer_parameter_config.exe")
  set_tests_properties(JammerParameterConfigTest PROPERTIES  LABELS "unit;config;jammer" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;215;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(JammerParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_jammer_parameter_config.exe")
  set_tests_properties(JammerParameterConfigTest PROPERTIES  LABELS "unit;config;jammer" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;215;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(JammerParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_jammer_parameter_config.exe")
  set_tests_properties(JammerParameterConfigTest PROPERTIES  LABELS "unit;config;jammer" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;215;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(JammerParameterConfigTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ReceiveParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_receive_parameter_config.exe")
  set_tests_properties(ReceiveParameterConfigTest PROPERTIES  LABELS "unit;config;receive" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;216;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ReceiveParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/Release/test_receive_parameter_config.exe")
  set_tests_properties(ReceiveParameterConfigTest PROPERTIES  LABELS "unit;config;receive" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;216;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ReceiveParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_receive_parameter_config.exe")
  set_tests_properties(ReceiveParameterConfigTest PROPERTIES  LABELS "unit;config;receive" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;216;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ReceiveParameterConfigTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_receive_parameter_config.exe")
  set_tests_properties(ReceiveParameterConfigTest PROPERTIES  LABELS "unit;config;receive" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;216;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(ReceiveParameterConfigTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SimpleReceiveTest "D:/code/signal-transmission-model-cpp/bin/Debug/simple_receive_test.exe")
  set_tests_properties(SimpleReceiveTest PROPERTIES  LABELS "unit;simple" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;219;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SimpleReceiveTest "D:/code/signal-transmission-model-cpp/bin/Release/simple_receive_test.exe")
  set_tests_properties(SimpleReceiveTest PROPERTIES  LABELS "unit;simple" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;219;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SimpleReceiveTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/simple_receive_test.exe")
  set_tests_properties(SimpleReceiveTest PROPERTIES  LABELS "unit;simple" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;219;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SimpleReceiveTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/simple_receive_test.exe")
  set_tests_properties(SimpleReceiveTest PROPERTIES  LABELS "unit;simple" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;219;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(SimpleReceiveTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BasicIntegrationTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_integration.exe")
  set_tests_properties(BasicIntegrationTest PROPERTIES  LABELS "integration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;222;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BasicIntegrationTest "D:/code/signal-transmission-model-cpp/bin/Release/test_integration.exe")
  set_tests_properties(BasicIntegrationTest PROPERTIES  LABELS "integration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;222;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BasicIntegrationTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_integration.exe")
  set_tests_properties(BasicIntegrationTest PROPERTIES  LABELS "integration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;222;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BasicIntegrationTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_integration.exe")
  set_tests_properties(BasicIntegrationTest PROPERTIES  LABELS "integration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;222;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(BasicIntegrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnvironmentLossMigrationTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_environment_loss_migration.exe")
  set_tests_properties(EnvironmentLossMigrationTest PROPERTIES  LABELS "integration;migration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;225;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnvironmentLossMigrationTest "D:/code/signal-transmission-model-cpp/bin/Release/test_environment_loss_migration.exe")
  set_tests_properties(EnvironmentLossMigrationTest PROPERTIES  LABELS "integration;migration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;225;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnvironmentLossMigrationTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_environment_loss_migration.exe")
  set_tests_properties(EnvironmentLossMigrationTest PROPERTIES  LABELS "integration;migration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;225;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnvironmentLossMigrationTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_environment_loss_migration.exe")
  set_tests_properties(EnvironmentLossMigrationTest PROPERTIES  LABELS "integration;migration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;225;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(EnvironmentLossMigrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(PathLossMigrationTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_path_loss_migration.exe")
  set_tests_properties(PathLossMigrationTest PROPERTIES  LABELS "integration;migration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;226;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(PathLossMigrationTest "D:/code/signal-transmission-model-cpp/bin/Release/test_path_loss_migration.exe")
  set_tests_properties(PathLossMigrationTest PROPERTIES  LABELS "integration;migration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;226;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(PathLossMigrationTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_path_loss_migration.exe")
  set_tests_properties(PathLossMigrationTest PROPERTIES  LABELS "integration;migration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;226;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(PathLossMigrationTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_path_loss_migration.exe")
  set_tests_properties(PathLossMigrationTest PROPERTIES  LABELS "integration;migration" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;226;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(PathLossMigrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FreeSpacePathLossRefactorTest "D:/code/signal-transmission-model-cpp/bin/Debug/test_free_space_path_loss_refactor.exe")
  set_tests_properties(FreeSpacePathLossRefactorTest PROPERTIES  LABELS "integration;refactor" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;227;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(FreeSpacePathLossRefactorTest "D:/code/signal-transmission-model-cpp/bin/Release/test_free_space_path_loss_refactor.exe")
  set_tests_properties(FreeSpacePathLossRefactorTest PROPERTIES  LABELS "integration;refactor" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;227;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(FreeSpacePathLossRefactorTest "D:/code/signal-transmission-model-cpp/bin/MinSizeRel/test_free_space_path_loss_refactor.exe")
  set_tests_properties(FreeSpacePathLossRefactorTest PROPERTIES  LABELS "integration;refactor" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;227;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(FreeSpacePathLossRefactorTest "D:/code/signal-transmission-model-cpp/bin/RelWithDebInfo/test_free_space_path_loss_refactor.exe")
  set_tests_properties(FreeSpacePathLossRefactorTest PROPERTIES  LABELS "integration;refactor" TIMEOUT "60" _BACKTRACE_TRIPLES "D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;227;add_test;D:/code/signal-transmission-model-cpp/tests/CMakeLists.txt;0;")
else()
  add_test(FreeSpacePathLossRefactorTest NOT_AVAILABLE)
endif()
subdirs("../_deps/googletest-build")
